global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx-metrics:9113'] 

  - job_name: 'docker'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080'] 

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100'] 

  - job_name: 'kafka'
    scrape_interval: 5s
    static_configs:
      - targets: ['kafka:1234']