name: clang-format
on: [pull_request]
jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: check-formatting
      shell: bash
      run: |
        echo $GITHUB_BASE_REF
        echo $GITHUB_HEAD_REF
        sudo apt-get update
        sudo apt-get install -y clang-format 
        formatterOutput=$(git clang-format --diff $GITHUB_BASE_REF $GITHUB_HEAD_REF)
        if [ "$formatterOutput" != "clang-format did not modify any files" ] &&
           [ "$formatterOutput" != "no modified files to format" ]
        then
          echo "$formatterOutput"
          exit 1
        fi
        
        echo "$formatterOutput"
