name: deploy
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: connect to ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ssh_host }}
          username: ${{ secrets.ssh_user }}
          key: ${{ secrets.ssh_key }}
          port: ${{ secrets.ssh_port }}
          script: | 
            cd Desbordante
            git pull origin Docker
            docker build -t cpp-consumer -f=Dockerfile-cpp-consumer .
            unzip datasets/datasets.zip -d volumes/datasets/
            docker-compose down
            docker-compose build
            docker-compose up --force-recreate
